# -*- coding: utf-8 -*-
"""BeautifulSoup(Ryans).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y4TYc9sQLqwzRCgUwFTlC-jPlaKJ9dTy
"""

!pip install beautifulsoup4
!pip install requests

"""# **Step:01 Import Library**"""

from bs4 import BeautifulSoup
import requests
import pandas as pd

url='https://www.ryanscomputers.com/category/laptop-all-laptop?limit=100&osp=0'

user_agent=user_agent = {'User-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36'}
response  = requests.get(url, headers = user_agent)

Soup= BeautifulSoup(response.text,'lxml')
Soup

for i in Soup.find_all('a'):
   print(i.get('href'))

products = Soup.find_all('div', {'class': 'card-body text-center'})
for product in products:
    print(product.find('p', {'class': 'card-text p-0 m-0 list-view-text'}).get_text())
    print(product.find('ul').find_all('li')[0].get_text())
    print(product.find('ul').find_all('li')[1].get_text())
    print(product.find('ul').find_all('li')[2].get_text())
    print(product.find('ul').find_all('li')[3].get_text())
    print(product.find('ul').find_all('li')[4].get_text())
    print(product.find('ul').find_all('li')[5].get_text())
    print(product.find('p', {'class': 'card-text p-0 m-0 list-view-text'}).find('a').get('href'))
    print(product.find('p', {'class': 'pr-text cat-sp-text pb-1'}).get_text())

html=""""<!DOCTYPE HTML>
<html>
<head>
<meta charset=utf-8">
<title>A Simple HTML Example</title>
<style>
p {text-align:center;}
</style>
</head>
<body>
<h1>This is a header</h1>
<p>This is a paragraph, centered on the page.</p>
<p>And this is the second paragraph with <strong>bold text</strong>.</p>
</body>
</html>"""

Soup= BeautifulSoup(html,'html.parser')
Soup

Soup.find('h1').get_text()

Soup.find('p').get_text()

for i in Soup.find_all('p'):
  print(i.get_text())

